language: ruby
rvm:
  - 2.0.0
before_script:
  - psql -c 'create database nine_one_one' -U postgres
  - psql -c 'create extension postgis;' -U postgres nine_one_one
env:
  - DB=postgres://localhost/nine_one_one
